name: RELEASE
on:
  push:
    branches:
      - master

jobs:
  release:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: setup private registry with token
        uses: adaptabletools/release-library@v1.1
        env:
          PRIVATE_REGISTRY_TOKEN: ${{ secrets.NPM_REGISTRY_TOKEN }}

      - name: Echo whoami
        run: npm whoami --registry=https://registry.adaptabletools.com

      - name: Echo publish cmd
        run: echo $PUBLISH_PACKAGE_CMD

      - name: Executing npm install in root
        run: npm i

      - name: git status
        run: git status

      - name: Set git config
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"

      - name: Actually publish to private registry
        run: node ./registry-publish.js

      - name: git status
        run: git status

      - name: git log
        run: git log

      - name: git remote
        run: git remote -v

      - name: git log origin/master..HEAD
        run: git log origin/master..HEAD

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.DEPLOY_GITHUB_TOKEN }}
